name: build
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install sfdx-cli    
      - name: Populate auth file
        run: 'echo "${{ secrets.SALESFORCE_AUTH_URL }}" > .SALESFORCE_AUTH_URL.txt'
      - name: Authenticate Dev Hub
        run: 'node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f .SALESFORCE_AUTH_URL.txt -a devhub -d'
      - name: Set Default Username
        run: node_modules/sfdx-cli/bin/run config:set defaultusername=devhub
      - name: Deploy to Production
        run: node_modules/sfdx-cli/bin/run force:source:deploy --verbose --sourcepath force-app -l RunLocalTests -c
